services:
  backend:
    build: ./backend
    container_name: ActixPostgresReact-Backend
    ports:
      - "8080:8080"
    restart: on-failure
  postgres:
    image: postgres:latest
    container_name: ActixPostgresReact-DB
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=database
  frontend:
    build: ./frontend
    container_name: ActixPostgresReact-Frontend
    ports:
      - "80:80"
    restart: on-failure
volumes:
  db: