[package]
name = "ActixPostgresReact-Backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-web = "4.8.0"
dotenv = "0.15.0"
serde_json = "1.0.122"
tokio-postgres = "0.7.2"
tokio = { version = "1.39.2", features = ["full"] }